### ISSUE TITLE
Acesso ao banco Next

### ISSUE THREAD

**Issue by jeffbzrr** [andreroggeri/pybradesco#1]
Seria possível utilizar o pybradesco para acessar o banco next? Pelo que vi eles compartilham a mesma api.

**Comment by andreroggeri** [comment]
Não sei... Mas aqui é feito tudo pelo browser, então imagino que seria tudo diferente.

**Comment by jeffbzrr** [comment]
Peguei uma conta do banco Next. Descobrirei em breve.

**Comment by jeffbzrr** [comment]
Pelo que vi o banco next não tem acesso web.

**Comment by marcelocecin** [comment]
vc usa iOS ou Android ? uma forma seria tentar monitorar as requisições que o app faz, mas é muito provável que seja protegido com handshake

**Comment by jeffersonmsb** [comment]
Uso Android. Quero tentar monitorar as requisições.

**Comment by jeffbzrr** [comment]
Uso Android. Quero tentar monitorar as requisições. O que pesquiso pra aprender fazer isso?

**Comment by marcelocecin** [comment]
https://proxyman.io/posts/2020-09-19-Intercept-https-traffic-on-android-emulator

https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/
